// apps/web/src/pages/Analyst-Tabs/RegionalReports.jsx
import { useCallback, useEffect, useState } from 'react';
import apiClient from '../../lib/api';

const REGIONS = ['NCR', 'CAR', 'Region I', 'Region II', 'Region III', 'Region IV-A', 'MIMAROPA', 'Region V', 'Region VI', 'Region VII', 'Region VIII', 'Region IX', 'Region X', 'Region XI', 'Region XII', 'Region XIII', 'BARMM'];

export default function RegionalReports() {
  const [region, setRegion] = useState('');
  const [dateFrom, setFrom] = useState('');
  const [dateTo, setTo] = useState('');
  const [scamType, setScamType] = useState('all');
  const [rows, setRows] = useState([]);
  const [profile, setProfile] = useState(null);
  const [showPreview, setShowPreview] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const inputS = { padding: '8px 12px', borderRadius: '8px', fontSize: '12px', background: '#080810', border: '1px solid #1a1a2a', color: '#e2e8f0', outline: 'none' };
  const card = { borderRadius: '12px', padding: '20px', background: '#0e0e18', border: '1px solid #1a1a2a' };
  const thS = { textAlign: 'left', paddingBottom: '8px', fontWeight: 500, color: '#4b5563', fontFamily: "'JetBrains Mono',monospace", fontSize: '9px', letterSpacing: '0.06em' };
  const tdS = { padding: '10px 0', fontSize: '12px', borderTop: '1px solid #13131e' };
  const loadProfile = useCallback(async () => { try { const response = await apiClient.get('/api/v1/admin/profile'); setProfile(response.data?.data || null); } catch {} }, []);
  const loadReport = useCallback(async () => {
    try { setLoading(true); setError(''); const response = await apiClient.get('/api/v1/admin/reports', { params: { region: region || undefined, from: dateFrom || undefined, to: dateTo || undefined, scamType } }); setRows(response.data?.data || []); }
    catch (err) { setError(err.response?.data?.message || 'Could not generate the report.'); }
    finally { setLoading(false); }
  }, [region, dateFrom, dateTo, scamType]);
  useEffect(() => { loadProfile(); }, [loadProfile]);
  useEffect(() => { loadReport(); }, [loadReport]);
  function triggerSuccess() { setShowSuccess(true); setTimeout(() => setShowSuccess(false), 3000); }
  function handleGenerateReport() { setShowPreview(true); loadReport(); triggerSuccess(); }
  function handleExportCSV() { const headers = ['Region', 'Total Reports', 'Top Scam Type', 'Highest Reported Number', 'WoW Change']; const csv = [headers, ...rows.map((row) => [row.region, row.reports, row.topScamType, row.topNumber || '', row.weekOverWeek == null ? '' : `${(row.weekOverWeek * 100).toFixed(1)}%`])].map((line) => line.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = `sentinelph-regional-report-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); triggerSuccess(); }
  function handleExportPDF() { window.print(); triggerSuccess(); }
  const totalReports = rows.reduce((sum, row) => sum + row.reports, 0);
  const permittedRegions = profile?.jurisdiction && profile.jurisdiction !== 'National / Regional' ? [profile.jurisdiction] : REGIONS;
  return <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
    {/* Filters */}
    <div style={card}><div style={{ fontSize: '13px', fontWeight: 600, color: '#fff', marginBottom: '16px' }}>Report Filters</div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '12px', marginBottom: '16px' }}><div><div style={{ fontSize: '10px', marginBottom: '6px', color: '#6b7280', fontFamily: "'JetBrains Mono',monospace", letterSpacing: '0.06em' }}>REGION</div><select value={region} onChange={(event) => setRegion(event.target.value)} style={{ ...inputS, width: '100%' }}><option value="">{profile?.jurisdiction === 'National / Regional' ? 'All Regions' : 'My assigned scope'}</option>{permittedRegions.map((item) => <option key={item} value={item}>{item}</option>)}</select></div><div><div style={{ fontSize: '10px', marginBottom: '6px', color: '#6b7280', fontFamily: "'JetBrains Mono',monospace", letterSpacing: '0.06em' }}>SCAM TYPE</div><select value={scamType} onChange={(event) => setScamType(event.target.value)} style={{ ...inputS, width: '100%' }}><option value="all">All Types</option><option>OTP Phishing</option><option>Bank Impersonation</option><option>Investment Scam</option><option>Parcel/Delivery</option><option>Gov't Impersonation</option></select></div><div><div style={{ fontSize: '10px', marginBottom: '6px', color: '#6b7280', fontFamily: "'JetBrains Mono',monospace", letterSpacing: '0.06em' }}>DATE FROM</div><input type="date" value={dateFrom} onChange={(event) => setFrom(event.target.value)} style={{ ...inputS, width: '100%', boxSizing: 'border-box' }}/></div><div><div style={{ fontSize: '10px', marginBottom: '6px', color: '#6b7280', fontFamily: "'JetBrains Mono',monospace", letterSpacing: '0.06em' }}>DATE TO</div><input type="date" value={dateTo} onChange={(event) => setTo(event.target.value)} style={{ ...inputS, width: '100%', boxSizing: 'border-box' }}/></div></div><div style={{ display: 'flex', gap: '8px' }}><button onClick={handleGenerateReport} disabled={loading} style={{ padding: '10px 20px', borderRadius: '10px', fontSize: '13px', fontWeight: 600, background: '#a855f7', color: '#fff', border: 'none', cursor: 'pointer' }}>{loading ? 'Generating…' : 'Generate Report'}</button><button onClick={handleExportCSV} disabled={!rows.length} style={{ padding: '10px 16px', borderRadius: '10px', fontSize: '12px', fontWeight: 500, background: '#111120', border: '1px solid #1a1a2a', color: '#9ca3af', cursor: rows.length ? 'pointer' : 'not-allowed', opacity: rows.length ? 1 : .5 }}>Export CSV</button><button onClick={handleExportPDF} style={{ padding: '10px 16px', borderRadius: '10px', fontSize: '12px', fontWeight: 500, background: '#111120', border: '1px solid #1a1a2a', color: '#9ca3af', cursor: 'pointer' }}>Export PDF</button></div></div>
    {error && <div style={{ ...card, borderColor: '#ef444466', color: '#fca5a5', fontSize: '12px' }}>{error}</div>}
    {showSuccess && <div style={{ padding: '12px 16px', borderRadius: '10px', fontSize: '13px', fontWeight: 500, background: '#0a1a12', border: '1px solid #22c55e40', color: '#22c55e', display: 'flex', alignItems: 'center', gap: '10px', animation: 'fadeIn 0.3s ease' }}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#22c55e" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6L9 17l-5-5"/></svg>Action completed successfully.</div>}
    {/* Generated Preview Panel */}
    {showPreview && <div style={{ ...card, borderLeft: '4px solid #a855f7' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px' }}><div><div style={{ fontSize: '13px', fontWeight: 600, color: '#fff' }}>Generated Report Preview</div><div style={{ fontSize: '11px', color: '#4b5563', marginTop: '2px' }}>Based on filters: {region || profile?.jurisdiction || 'All Regions'} · {dateFrom || 'All dates'} to {dateTo || 'today'}</div></div><button onClick={() => setShowPreview(false)} style={{ fontSize: '11px', color: '#6b7280', background: 'none', border: 'none', cursor: 'pointer' }}>Hide</button></div><div style={{ padding: '16px', borderRadius: '10px', background: '#080810', border: '1px solid #13131e', fontSize: '12px', color: '#9ca3af', lineHeight: 1.7 }}><strong style={{ color: '#fff' }}>Summary:</strong> {rows.length} regions analyzed with a combined {totalReports.toLocaleString()} reports.{rows[0] && <> Highest activity in <span style={{ color: '#a855f7', fontWeight: 600 }}>{rows[0].region}</span> with {rows[0].reports.toLocaleString()} reports{rows[0].weekOverWeek == null ? '.' : ` (${rows[0].weekOverWeek >= 0 ? '+' : ''}${(rows[0].weekOverWeek * 100).toFixed(1)}% WoW).`}</>}</div></div>}
    {/* Data preview */}
    <div style={card}><div style={{ fontSize: '13px', fontWeight: 600, color: '#fff', marginBottom: '4px' }}>Data Preview — Live Agency Scope</div><div style={{ fontSize: '11px', color: '#4b5563', marginBottom: '16px' }}>Showing regions by report volume</div><table style={{ width: '100%', borderCollapse: 'collapse' }}><thead><tr>{['REGION', 'TOTAL REPORTS', 'TOP SCAM TYPE', 'HIGHEST REPORTED NUMBER', 'WOW CHANGE'].map((heading) => <th key={heading} style={thS}>{heading}</th>)}</tr></thead><tbody>{!loading && rows.length === 0 ? <tr><td colSpan="5" style={{ ...tdS, color: '#4b5563', textAlign: 'center' }}>No reports match these filters.</td></tr> : rows.map((row) => { const wow = row.weekOverWeek == null ? '—' : `${row.weekOverWeek >= 0 ? '+' : ''}${(row.weekOverWeek * 100).toFixed(1)}%`; return <tr key={row.region}><td style={{ ...tdS, fontWeight: 600, color: '#fff' }}>{row.region}</td><td style={{ ...tdS, fontWeight: 700, color: '#fff', fontFamily: "'JetBrains Mono',monospace" }}>{row.reports.toLocaleString()}</td><td style={{ ...tdS, color: '#a855f7' }}>{row.topScamType}</td><td style={{ ...tdS, color: '#9ca3af', fontFamily: "'JetBrains Mono',monospace" }}>{row.topNumber || '—'}</td><td style={{ ...tdS, fontWeight: 600, color: row.weekOverWeek == null ? '#6b7280' : row.weekOverWeek >= 0 ? '#ef4444' : '#22c55e', fontFamily: "'JetBrains Mono',monospace" }}>{wow}</td></tr>; })}</tbody></table></div>
    {/* Existing section retained; scheduling requires a job runner before it can be enabled. */}
    <div style={card}><div style={{ fontSize: '13px', fontWeight: 600, color: '#fff', marginBottom: '16px' }}>Scheduled Reports</div><div style={{ padding: '12px 0', color: '#4b5563', fontSize: '12px', borderTop: '1px solid #13131e' }}>No scheduled exports are configured yet. Generate a live report above and export it when needed.</div></div>
    <style>{'@keyframes fadeIn { from { opacity: 0; transform: translateY(-6px); } to { opacity: 1; transform: translateY(0); } }'}</style>
  </div>;
}
